import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    // <div>
    //   <Head>
    //     {/* <div>hulu 2.0</div> */}
    //     <title>hulu 2.0</title>
    //   </Head>
    //   <Header />
    // </div>

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* what we need to build */}
      {/* Header component */}
      <Header />
      {/* Nav component */}
      <Navbar />
      {/* Result component */}

      <h1 className="text-3xl font-bold underline">Hello world!</h1>

      <br></br>
      {/* {footer - built in page but better to build it as component and import on page [or use layouts] that way can reuse on other pages} */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
